package com.ptw.ptw.enums;

public enum PermitStatus {

    DRAFT,
    SUBMITTED,
    ACCEPTOR_VERIFICATION,
    ACCEPTOR_VERIFIED,
    RETURNED,
    ELECTRICAL_ISOLATION,
    ISSUER_APPROVAL,
    ISSUER_VERIFICATION,
    ACCEPTOR_ACCEPTANCE,
    READY_FOR_PRINT,
    PRINTED,
    ACCEPTED,
    ACTIVE,
    EXTENDED,
    SUSPENDED,
    TERMINATED,
    REVALIDATION,
    WORK_COMPLETED,
    FINAL_VERIFICATION,
    CLOSED
}
