package com.ptw.ptw.enums;

public enum PermitWorkflowAction {

    ELECTRICAL_ISOLATION,
    EXTENDED,
    WORK_COMPLETED,
    CLOSED,
    DRAFT,
    PERMIT_IN_PROGRESS,
    PERMIT_ISSUED,
    WORK_IN_PROGRESS,
    ISSUER_APPROVED,
    ASSESSMENT_COMPLETED,
    EXTENSION_REQUESTED,
    EXTENSION_ACCEPTED,
    EXTENSION_REJECTED,
    EXTENSION_PRINTED

}